spring:
  application:
    name: Persistence
  datasource:
    url: jdbc:postgresql://localhost:5432/jpa_db
    username: guardian
    password: guarddb:0
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true    

